# Site settings
title: Wrocław Biofilm Symposium
description: "Wrocław Biofilm Symposium. Amyloidic origins of biofilms - from formation to dispersion. Wrocław, Poland, 9-10.10.2017"
baseurl: ""
url: ""
logo_url: svg/logo.svg

#git seetings
safe: true
gist:
    noscript: false

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Wrocław Biofilm Symposium 
    hero_description: Amyloidic origins of biofilms - from formation to dispersion.

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    email: biofilmsymposium@biotech.uni.wroc.pl
    address: Faculty of Biotechnology <br> University of Wrocław <br> Fryderyka Joliot-Curie 14a <br> 50-383 Wrocław, Poland

# Opening hours
day1: 12:00 – 19:00
day2: 08:30 – 14:00


# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 15.5
    address: Fryderyka Joliot-Curie 14a, 50-383 Wrocław
    address_details: svg/min/logo.svg

# Social settings
# facebook: http://facebook.com
# twitter: http://twitter.com
# instagram: http://instagram.com
# youtube: http://youtube.com
# skype: skype:obaez_design?userinfo
# feed: yes

# Footer
copyright: © 2015 DentistSmile - All rights reserved (modified by Michał Burdukiewicz)

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore,
    biofilm_conference.Rproj,
    wroclaw-biofilm-symposium.Rproj
]

# Theme Settings
analytics: 
google_verification:
